---
title: "GETTING STARTED WITH QUARTO"
author: "Kasim Chambulilo"
format: 
  html: default
  pdf: default
editor: visual
execute: 
  echo: false
---

# Introduction

## Data {.smaller}

For this analysis we'll use the penguins data set from the [palmerpenguins](https://gist.github.com/slopp/ce3b90b9168f2f921784de84fa445651) data set

```{r}
library(tidyverse)
library(ggthemes)
library(palmerpenguins)
library(gt)
library(dplyr)
library(ggplot2)
```

```{r}
glimpse(penguins)
```

**Species**

The figure below is a scatter plot of species of penguins.

```{r}
#| label: fig-bill-dims-species
#| fig-width: 5
#| fig-asp: 0.618
#| fig-alt: 
#|    A scatter plot of penguins' bill depth and length, colored by species of penguins. There is a relatively strong, linear association.
#| fig-cap:
#|      A scatter plot of penguins' bill depth and length, colored by species of penguins. There is a relatively strong, linear association.


ggplot(
  penguins,
  aes(
    x = bill_length_mm, y = bill_depth_mm,      color = species, shape = species
  )
) +
  geom_point() +
  theme_minimal() +
  scale_color_colorblind() +
  labs(x = "Bill lenght (mm)", y = "Bill depth (mm)")

```

**Penguins**

@tbl-penguins-top10 shows the first 10 penguins from the dataset

```{r}
#| label: tbl-penguins-top10
#| tbl-cap: First 10 penguins.

penguins |>
  slice_head(n = 10) |>
  select(species, island, bill_length_mm, bill_depth_mm) |>
  gt()

```
